-- Auto-generated INSERT statements from MonStock_all.csv

-- Truncate existing products (optional - comment out if you want to keep existing data)
-- TRUNCATE TABLE public.products CASCADE;

INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'ACQUA DI SALE',
    'PROFUMUM ROMA',
    'HOMME',
    NULL,
    NULL,
    '69',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'LA VIE EST BELLE',
    'LANCOME',
    'FEMME',
    NULL,
    NULL,
    '42',
    11.9,
    18.0,
    35.0,
    2,
    0,
    0,
    2,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'OMBRE LEATHER',
    'TOM FORD',
    'MIXTES L£UXES',
    NULL,
    NULL,
    '142',
    0.0,
    0.0,
    57.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'CRYSTAL NOIR',
    'VERSACE',
    'FEMME',
    NULL,
    NULL,
    '47',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'SIGNORINA',
    'FERRAGAMO',
    'FEMME',
    NULL,
    NULL,
    '82',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'MEGAMARE',
    'ORTO PARISI',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '130',
    0.0,
    0.0,
    65.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'LE MÂLE',
    'JPG',
    'HOMME',
    NULL,
    NULL,
    '16',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'GOOD GIRL GONE BAD',
    'KILLIAN',
    'LUXURY FEMME',
    NULL,
    NULL,
    '123',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'GOOD GIRL',
    'CAROLINA HERRERA',
    'FEMME LUXE',
    NULL,
    NULL,
    '131',
    0.0,
    0.0,
    48.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'MYSLF',
    'YSL',
    'HOMME',
    NULL,
    NULL,
    '79',
    11.9,
    18.0,
    35.0,
    3,
    1,
    0,
    2,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'MISS DIOR CHÉRIE',
    'DIOR',
    'FEMME',
    NULL,
    NULL,
    '39',
    11.9,
    18.0,
    35.0,
    2,
    0,
    0,
    2,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'AMO',
    'FERRAGAMO',
    'FEMME',
    NULL,
    NULL,
    '97',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'OPIUM',
    'YSL',
    'FEMME',
    NULL,
    NULL,
    '6',
    11.9,
    18.0,
    35.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'MON PARIS',
    'YSL',
    'FEMME',
    NULL,
    NULL,
    '89',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'HUGO',
    'HUGO BOSS',
    'FEMME',
    NULL,
    NULL,
    '156W ( 063-263)',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'COCO MADEMOISELLE',
    'CHANEL',
    'FEMME',
    NULL,
    NULL,
    '51',
    11.9,
    18.0,
    35.0,
    2,
    0,
    2,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'THE SCENT',
    'HUGO BOSS',
    'HOMME',
    NULL,
    NULL,
    '157M (065-265)',
    11.9,
    18.0,
    35.0,
    2,
    0,
    1,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'AVENTUS',
    'CREED',
    'HOMME LUXE',
    NULL,
    NULL,
    '68',
    0.0,
    0.0,
    57.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'ONE MILLION',
    'PACO RABANNE',
    'HOMME',
    NULL,
    NULL,
    '1',
    11.9,
    18.0,
    35.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'LEGEND',
    'MONT BLANC',
    'HOMME',
    NULL,
    NULL,
    '86',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'LOVE CHLOÉ',
    'CHLOÉ',
    'FEMME',
    NULL,
    NULL,
    '154W (043-243)',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'Goddess',
    'BURBERRY',
    'FEMME',
    NULL,
    NULL,
    '148W',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'OLYMPEA',
    'PACO RABANNE',
    'FEMME',
    NULL,
    NULL,
    '67',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'LIGHT BLUE',
    'D&G',
    'HOMME',
    NULL,
    NULL,
    '21',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'KIRKÉ',
    'TIZIANA TERENZI',
    'MIXTES L£UXES',
    NULL,
    NULL,
    '110',
    0.0,
    0.0,
    48.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'ÉROS',
    'VERSACE',
    'HOMME',
    NULL,
    NULL,
    '140',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'JOY',
    'DIOR',
    'FEMME',
    NULL,
    NULL,
    '98',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'IDOLE',
    'LANCOME',
    'FEMME',
    NULL,
    NULL,
    '115',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'LA NUIT DE L''HOMME',
    'YSL',
    'HOMME',
    NULL,
    NULL,
    '20',
    11.9,
    18.0,
    35.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'EAU SAUVAGE',
    'DIOR',
    'HOMME',
    NULL,
    NULL,
    '12',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'BIANCO LATTE',
    'GIARDINI DI TOSCANA',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '144',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'THE ONE',
    'D&G',
    'FEMME',
    NULL,
    NULL,
    '70',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'SAUVAGE',
    'DIOR',
    'HOMME LUXE',
    NULL,
    NULL,
    '94',
    0.0,
    0.0,
    48.0,
    6,
    2,
    1,
    3,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'OMBRE NOMADE',
    'LOUIS VUITTON',
    'MIXTES L£UXES',
    NULL,
    NULL,
    '114',
    0.0,
    0.0,
    48.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'SOLE DI POSITANO ACQUA',
    'TOM FORD',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '125',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'SUR LA ROUTE',
    'LOUIS VUITTON',
    'HOMME LUXE',
    NULL,
    NULL,
    '113',
    17.9,
    29.5,
    57.0,
    2,
    1,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'HYPNOTIC POISON',
    'DIOR',
    'FEMME',
    NULL,
    NULL,
    '23',
    11.9,
    18.0,
    35.0,
    3,
    0,
    0,
    3,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'BLEU',
    'CHANEL',
    'HOMME',
    NULL,
    NULL,
    '38',
    11.9,
    18.0,
    35.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'FILLE',
    'Sans Marque',
    'FILLE',
    NULL,
    NULL,
    '58',
    0.0,
    0.0,
    29.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'LIGHT BLUE',
    'D&G',
    'FEMME',
    NULL,
    NULL,
    '11',
    11.9,
    18.0,
    35.0,
    2,
    0,
    2,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'CHANCE',
    'CHANEL',
    'FEMME',
    NULL,
    NULL,
    '85',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'BURBERRY WOMEN',
    'BURBERRY',
    'FEMME',
    NULL,
    NULL,
    '159W (095-295)',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'J''ADORE L''OR',
    'DIOR',
    'LUXURY FEMME',
    NULL,
    NULL,
    '109',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'SI',
    'ARMANI',
    'FEMME',
    NULL,
    NULL,
    '80',
    11.9,
    18.0,
    35.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'ERBA PURA',
    'XERJOFF',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '129',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'VELVET AMBER SKIN',
    'D&G',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '101',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'HIMALAYA',
    'CREED',
    'MIXTES L£UXES',
    NULL,
    NULL,
    '73',
    0.0,
    0.0,
    48.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'CHLOÉ',
    'CHLOÉ',
    'FEMME',
    NULL,
    NULL,
    '153W (041-241)',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'OMNIA INDIAN GARNET',
    'BVLGARI',
    'FEMME',
    NULL,
    NULL,
    '64',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'SPICE BOMB',
    'VIKTOR & ROLF',
    'HOMME',
    NULL,
    NULL,
    '32',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'THE ONE',
    'D&G',
    'HOMME',
    NULL,
    NULL,
    '4',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'BLACK ORCHID',
    'TOM FORD',
    'MIXTE',
    NULL,
    NULL,
    '54',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'L''INTERDIT',
    'GIVENCHY',
    'FEMME',
    NULL,
    NULL,
    '121',
    11.9,
    18.0,
    35.0,
    2,
    0,
    0,
    2,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'HYPNOSE',
    'LANCOME',
    'FEMME',
    NULL,
    NULL,
    '40',
    11.9,
    18.0,
    35.0,
    2,
    0,
    0,
    2,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'SCANDAL',
    'JPG',
    'FEMME',
    NULL,
    NULL,
    '119',
    11.9,
    18.0,
    35.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'FUCKING FABULOUS',
    'TOM FORD',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '106',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'DÉCLARATION',
    'CARTIER',
    'HOMME',
    NULL,
    NULL,
    '18',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'XJ 1861 NAXOS',
    'XERJOFF',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '137',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'VELVET AMBER SUN',
    'D&G',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '102',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'PATCHOULI',
    'REMINISCENCE',
    'MIXTE',
    NULL,
    NULL,
    '72',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'FOR HER',
    'NARCISO RODRIGUEZ',
    'FEMME',
    NULL,
    NULL,
    '25',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'SILVER MOUNTAIN',
    'CREED',
    'MIXTES L£UXES',
    NULL,
    NULL,
    '44',
    0.0,
    0.0,
    48.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'MAN',
    'BVLGARI',
    'HOMME',
    NULL,
    NULL,
    '37',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'OUD WOOD',
    'TOM FORD',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '127',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'BLACK XS',
    'PACO RABANNE',
    'HOMME',
    NULL,
    NULL,
    '30',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'WOOD WHISPER',
    'OJAR',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '138',
    0.0,
    19.9,
    52.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'NARCISO',
    'NARCISO RODRIGUEZ',
    'FEMME',
    NULL,
    NULL,
    '53',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'AVENTUS FOR HER',
    'CREED',
    'FEMME LUXE',
    NULL,
    NULL,
    '93',
    0.0,
    0.0,
    57.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'ACQUA DI GIO',
    'ARMANI',
    'HOMME',
    NULL,
    NULL,
    '2',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'J''ADORE',
    'DIOR',
    'FEMME',
    NULL,
    NULL,
    '7',
    11.9,
    18.0,
    35.0,
    2,
    0,
    0,
    2,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'ANGEL',
    'THIERRY MUGLER',
    'FEMME',
    NULL,
    NULL,
    '28',
    11.9,
    18.0,
    35.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'GUILTY',
    'GUCCI',
    'HOMME',
    NULL,
    NULL,
    '152M (017-217)',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'NÉROLI PORTOFINO',
    'TOM FORD',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '112',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'BLACK OPIUM',
    'YSL',
    'FEMME',
    NULL,
    NULL,
    '55',
    11.9,
    18.0,
    35.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'DOLCE',
    'D&G',
    'FEMME',
    NULL,
    NULL,
    '49',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'VANILLA POWDER',
    'MATIÈRE PREMIÈRE',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '143',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'BLACK CODE',
    'ARMANI',
    'HOMME',
    NULL,
    NULL,
    '33',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'ALLURE',
    'CHANEL',
    'FEMME',
    NULL,
    NULL,
    '71',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'BITTER PEACH',
    'TOM FORD',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '134',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'TOBACCO VANILLE',
    'TOM FORD',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '117',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'GUILTY',
    'GUCCI',
    'FEMME',
    NULL,
    NULL,
    '151W (013-213)',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'CHANEL N°5',
    'CHANEL',
    'FEMME',
    NULL,
    NULL,
    '24',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'MAN IN BLACK',
    'BVLGARI',
    'HOMME',
    NULL,
    NULL,
    '88',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'L''EAU D''ISSEY',
    'ISSEY MIYAKE',
    'FEMME',
    NULL,
    NULL,
    '29',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'INTENSO',
    'D&G',
    'HOMME',
    NULL,
    NULL,
    '62',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'WHITE AOUD',
    'MONTALE',
    'MIXTE',
    NULL,
    NULL,
    '100',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'CHROME',
    'AZZARO',
    'HOMME',
    NULL,
    NULL,
    '91',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'LIBRE',
    'YSL',
    'FEMME LUXE',
    NULL,
    NULL,
    '122',
    14.9,
    25.5,
    48.0,
    3,
    2,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'BOSS Bottled Absolu',
    'HUGO BOSS',
    'HOMME',
    NULL,
    NULL,
    '147M',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'GABRIELLE',
    'CHANEL',
    'FEMME',
    NULL,
    NULL,
    '96',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'ZETA',
    'MORPH',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '124',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'PRADA PARADOXE',
    'PRADA',
    'FEMME',
    NULL,
    NULL,
    '133',
    11.9,
    18.0,
    35.0,
    4,
    0,
    2,
    2,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'HUGO',
    'HUGO BOSS',
    'HOMME',
    NULL,
    NULL,
    '150M (005-250)',
    11.9,
    18.0,
    35.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'LOST CHERRY',
    'TOM FORD',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '111',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'LADY MILLION',
    'PACO RABANNE',
    'FEMME',
    NULL,
    NULL,
    '19',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'GARÇON',
    'Sans Marque',
    'GARÇON',
    NULL,
    NULL,
    '45',
    0.0,
    0.0,
    29.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'LES SABLES ROSES',
    'LOUIS VUITTON',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '139',
    0.0,
    0.0,
    65.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'BEBE',
    'Sans Marque',
    'BEBE',
    NULL,
    NULL,
    '59',
    0.0,
    0.0,
    29.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'MANIFESTO',
    'YSL',
    'FEMME',
    NULL,
    NULL,
    '14',
    11.9,
    18.0,
    35.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'DIOR HOMME INTENSE',
    'DIOR',
    'HOMME LUXE',
    NULL,
    NULL,
    '136',
    13.9,
    23.5,
    45.0,
    2,
    0,
    1,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'MANDARINO DI AMALFI',
    'TOM FORD',
    'MIXTES L£UXES',
    NULL,
    NULL,
    '99',
    0.0,
    0.0,
    45.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'BACCARAT ROUGE 540',
    'MAISON F. KURKDJIAN',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '118',
    0.0,
    19.9,
    52.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'CK ONE',
    'CALVIN KLEIN',
    'MIXTE',
    NULL,
    NULL,
    '155U (046-246)',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'WANTED',
    'AZZARO',
    'HOMME',
    NULL,
    NULL,
    '87',
    0.0,
    0.0,
    0.0,
    3,
    0,
    0,
    3,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'X FOR MEN',
    'CLIVE CHRISTIAN',
    'LUXURY HOMME',
    NULL,
    NULL,
    '75',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'ALLURE HOMME',
    'CHANEL',
    'HOMME',
    NULL,
    NULL,
    '48',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'FLORA',
    'GUCCI',
    'FEMME',
    NULL,
    NULL,
    '158W (077-277)',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'VANILLE FATALE',
    'TOM FORD',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '128',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'DYLAN BLUE',
    'VERSACE',
    'HOMME',
    NULL,
    NULL,
    '84',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'Turath',
    'The Spirit of Dubaï',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '141',
    0.0,
    0.0,
    65.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'BLACK AFGANO',
    'NASOMATTO',
    'LUXURY HOMME',
    NULL,
    NULL,
    '74',
    0.0,
    19.9,
    52.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'ANGE OU DÉMON',
    'GIVENCHY',
    'FEMME',
    NULL,
    NULL,
    '56',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'ROMA UOMO',
    'LAURA BIAGIOTTI',
    'HOMME',
    NULL,
    NULL,
    '15',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'CLASSIQUE ESSENCE',
    'JPG',
    'FEMME',
    NULL,
    NULL,
    '81',
    11.9,
    18.0,
    35.0,
    3,
    0,
    2,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'LA PETITE ROBE NOIRE',
    'GUERLAIN',
    'FEMME',
    NULL,
    NULL,
    '120',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'TRÉSOR',
    'LANCOME',
    'FEMME',
    NULL,
    NULL,
    '27',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'BOIS D''ARGENT',
    'DIOR',
    'MIXTES L£UXES',
    NULL,
    NULL,
    '135',
    0.0,
    0.0,
    57.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'PASHA 150',
    'CARTIER',
    'HOMME',
    NULL,
    NULL,
    '52',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'DÉVOTION',
    'D&G',
    'FEMME',
    NULL,
    NULL,
    '145',
    11.9,
    18.0,
    35.0,
    8,
    0,
    3,
    5,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'BURBERRY FOR MEN',
    'BURBERRY',
    'HOMME',
    NULL,
    NULL,
    '160M (050-250)',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'OMNIA AMÉTHYSTE',
    'BVLGARI',
    'FEMME',
    NULL,
    NULL,
    '57',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'ACQUA DI GIOIA',
    'ARMANI',
    'FEMME',
    NULL,
    NULL,
    '76',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'POISON GIRL',
    'DIOR',
    'FEMME',
    NULL,
    NULL,
    '90',
    11.9,
    18.0,
    35.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'TERRE D’HERMÈS',
    'HERMÈS',
    'HOMME',
    NULL,
    NULL,
    '22',
    11.9,
    18.0,
    35.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'MY WAY',
    'ARMANI',
    'FEMME LUXE',
    NULL,
    NULL,
    '132',
    13.9,
    23.5,
    45.0,
    4,
    3,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'INTENSE CAFÉ',
    'MONTALE',
    'MIXTE',
    NULL,
    NULL,
    '105',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'YES I AM',
    'CACHAREL',
    'FEMME',
    NULL,
    NULL,
    '116',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'SOLEIL BLANC',
    'TOM FORD',
    'LUXURY MIXTES',
    NULL,
    NULL,
    '126',
    0.0,
    0.0,
    52.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'ALIEN',
    'THIERRY MUGLER',
    'FEMME',
    NULL,
    NULL,
    '10',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'FLOWER',
    'KENZO',
    'FEMME',
    NULL,
    NULL,
    '26',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'INVICTUS',
    'PACO RABANNE',
    'HOMME',
    NULL,
    NULL,
    '61',
    0.0,
    0.0,
    0.0,
    0,
    0,
    0,
    0,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'FAHRENHEIT',
    'DIOR',
    'HOMME',
    NULL,
    NULL,
    '3',
    11.9,
    18.0,
    35.0,
    1,
    0,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'THE SCENT INTENSE',
    'COSTUME NATIONAL',
    'HOMME',
    NULL,
    NULL,
    '66',
    11.9,
    18.0,
    35.0,
    2,
    1,
    0,
    1,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'IMPERATRIX',
    'OLFAZETA',
    'LUXURY HOMME',
    NULL,
    NULL,
    NULL,
    0.0,
    20.9,
    60.0,
    2,
    0,
    0,
    2,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'NADIR',
    'OLFAZETA',
    'LUXURY HOMME',
    NULL,
    NULL,
    NULL,
    0.0,
    20.9,
    60.0,
    3,
    0,
    0,
    3,
    2
);
INSERT INTO public.products (name, brand, category, cat_15ml, cat_30ml, cat_70ml, price_15ml, price_30ml, price_70ml, stock_total, stock_15ml, stock_30ml, stock_70ml, alert_threshold) VALUES (
    'ULTRAVIOLET',
    'PACO RABANNE',
    'HOMME',
    NULL,
    NULL,
    NULL,
    11.9,
    18.0,
    35.0,
    1,
    1,
    0,
    0,
    2
);